# Generated by Django 6.0.4 on 2026-04-28 20:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SeniorProjectApp', '0013_cartitem_usercart_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carausel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/default_image.png', max_length=255, verbose_name='image'),
        ),
    ]
